// Entity types enum for lookup data sources
export enum EntityType {
  CHARGE_PROFILE = 'Charge Profile',
  DRIVER_CHARGE_PROFILE = 'Driver Charge Profile',
  CHASSIS_OWNERS = 'Chassis Owners',
  CHASSIS_SIZES = 'Chassis Sizes',
  CHASSIS_TYPES = 'Chassis Types',
  CONTAINER_SIZES = 'Container Sizes',
  CONTAINER_TYPES = 'Container Types',
  CONTAINER_OWNERS = 'Container Owners',
  BRANCHES = 'Branches',
  DRIVER_PROFILE_TYPES = 'Driver Profile Types',
  CUSTOMER = 'Customer',
  PERMISSION_ROLES = 'Permission Roles',
  FLEET_OWNERS = 'Fleet Owners',
  CUSTOMER_FLEET = 'Customer Fleet',
  TIMEZONE_LIST = 'Timezone List',
  COMMODITIES = 'Commodities',
  CHASSIS = 'Chassis',
  TRUCKS = 'Trucks',
  CURRENCIES = 'Currencies',
  CHARGE_CODES = 'Charge Codes',
  DRIVER_PAY_GROUPS = 'Driver Pay Groups',
  CITY_GROUPS = 'City Groups',
  ZIP_CODE_GROUPS = 'Zip Code Groups',
  CSR = 'CSR',
  DRIVER_GROUPS = 'Driver Groups',
  CARRIER_GROUPS = 'Carrier Groups'
}

// Default pagination settings for each entity type
export const ENTITY_PAGINATION_CONFIG = {
  [EntityType.CHARGE_PROFILE]: { initial: 15, increment: 15, serverSide: false },
  [EntityType.DRIVER_CHARGE_PROFILE]: { initial: 30, increment: 30, serverSide: true },
  [EntityType.CHASSIS_OWNERS]: { initial: 30, increment: 30, serverSide: false },
  [EntityType.CHASSIS_SIZES]: { initial: 30, increment: 30, serverSide: false },
  [EntityType.CHASSIS_TYPES]: { initial: 30, increment: 30, serverSide: false },
  [EntityType.CONTAINER_SIZES]: { initial: 30, increment: 30, serverSide: false },
  [EntityType.CONTAINER_TYPES]: { initial: 30, increment: 30, serverSide: false },
  [EntityType.CONTAINER_OWNERS]: { initial: 30, increment: 30, serverSide: false },
  [EntityType.BRANCHES]: { initial: 30, increment: 30, serverSide: false },
  [EntityType.DRIVER_PROFILE_TYPES]: { initial: 30, increment: 30, serverSide: false },
  [EntityType.CUSTOMER]: { initial: 30, increment: 30, serverSide: false },
  [EntityType.PERMISSION_ROLES]: { initial: 30, increment: 30, serverSide: false },
  [EntityType.FLEET_OWNERS]: { initial: 30, increment: 30, serverSide: false },
  [EntityType.CUSTOMER_FLEET]: { initial: 30, increment: 30, serverSide: false },
  [EntityType.TIMEZONE_LIST]: { initial: 30, increment: 30, serverSide: false },
  [EntityType.COMMODITIES]: { initial: 30, increment: 30, serverSide: false },
  [EntityType.CHASSIS]: { initial: 30, increment: 30, serverSide: false },
  [EntityType.TRUCKS]: { initial: 30, increment: 30, serverSide: false },
  [EntityType.CURRENCIES]: { initial: 30, increment: 30, serverSide: false },
  [EntityType.CHARGE_CODES]: { initial: 30, increment: 30, serverSide: false },
  [EntityType.DRIVER_PAY_GROUPS]: { initial: 30, increment: 30, serverSide: false },
  [EntityType.CITY_GROUPS]: { initial: 30, increment: 30, serverSide: false },
  [EntityType.ZIP_CODE_GROUPS]: { initial: 30, increment: 30, serverSide: false },
  [EntityType.CSR]: { initial: 30, increment: 30, serverSide: false },
  [EntityType.DRIVER_GROUPS]: { initial: 30, increment: 30, serverSide: false },
  [EntityType.CARRIER_GROUPS]: { initial: 30, increment: 30, serverSide: false }
} as const; 