import { z } from 'zod';

// Base schema for common string patterns - Updated to match exportEntities.json
const Patterns = {
  Email: z.string().regex(/^([^@]+@[^@]+\\s*,\\s*)*[^@]+@[^@]+$/, { message: "Invalid email format. Please use a valid email address like 'user@example.com'." }),
  USZip: z.string({ invalid_type_error: "ZIP code must be text." }).regex(/^[0-9]{5}(-[0-9]{4})?$/, { message: "Invalid US ZIP code format." }),
  Username: z.string().regex(/^[a-z0-9]+$/, { message: "Username must be 3-50 alphanumeric characters." }),
  USZipExtended: z.string({ invalid_type_error: "ZIP code must be text." }).regex(/^(?=(.*\\d)).{2,}$/, { message: "Invalid extended US ZIP code format." }),
  USState: z.string().regex(/^[A-Z]{2}$/, { message: "State must be a 2-letter code." }),
  CountryCode: z.string().regex(/^[A-Z]{2}$/, { message: "Country must be a 2-letter code." }),
  Phone10: z.string({ invalid_type_error: "Phone number must be text." }).regex(/^(\+?[1-9]{1}[0-9]{1,14}|\(?\d{1,4}\)?[\s\-]?\d{1,4}[\s\-]?\d{1,4}[\s\-]?\d{1,4})$/, { message: "Phone number must be 10 digits." }),
  PhoneFormatted: z.string().regex(/^\d{3}-\d{3}-\d{4}$/, { message: "Phone number must be in the format." }),
  DateMMDDYYYY: z.string().regex(/^(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])-[0-9]{4}$/, { message: "Date must be in MM-DD-YYYY format." }), // Updated to match exportEntities
  DateSlashMMDDYYYY: z.string().regex(/^(0[1-9]|1[0-2])\/(0[1-9]|[12][0-9]|3[01])\/[0-9]{4}$/, { message: "Date must be in MM/DD/YYYY format." }),
  DateYYYYMMDD: z.string().regex(/^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$/, { message: "Date must be in YYYY-MM-DD format." }),
  DateFlexible: z.string().refine((val) => {
    // This will be handled by the moment.js validation in dateUtils
    return true;
  }, { message: "Date must be in a valid format (MM-DD-YYYY, MM/DD/YYYY, YYYY-MM-DD, DD-MM-YYYY, DD/MM/YYYY)." }),
  YesNo: z.string().regex(/^(Yes|No)$/, { message: "Value must be 'Yes' or 'No'." }).optional(),
  YesNoCaseInsensitive: z.string().regex(/^(yes|no|Yes|No|YES|NO)$/i, { message: "Value must be 'Yes' or 'No'." }),
  LoadTypePattern: z.string().regex(/^(Import|Export|Road)$/, { message: "Invalid Load Type." }),
  RoutesPattern: z.string().regex(/^(Pick And Run \+ Live|Pick And Run \+ Drop & Hook|Prepull \+ Drop & Hook|Prepull \+ Live|One Way Move|Pick And Run \+ Gray Pool|Prepull \+ Gray Pool|Shunt|Pick and Lift \+ Deliver and Lift \+ Return|Pick and Lift \+ Live)$/, { message: "Invalid Route." }),
  TrailerTypePattern: z.string().regex(/^(Dry Van|Reefer|Flat Bed|Drop Deck|Low Boy|Double Drop Deck)$/, { message: "Invalid Trailer Type." }),
  TrailerSizePattern: z.string().regex(/^(26'|40'|45'|48'|53')$/, { message: "Invalid Trailer Size." }),
  ChassisNumberPattern: z.string().regex(/^[A-Z0-9]{1,50}$/, { message: "Chassis Number must be 1-50 alphanumeric characters." }),
  ChassisLicensePattern: z.string().regex(/^[A-Z]{2,}$/, { message: "Chassis License must be at least 2 letters." }),
  EquipmentIDPattern: z.string({ invalid_type_error: "Equipment ID must be text." }).regex(/^[0-9]{1,50}$/, { message: "Equipment ID must be 1 to 50 digits." }),
  TrailerNumberPattern: z.string({ invalid_type_error: "Trailer Number must be text." }).regex(/^[0-9]{1,50}$/, { message: "Trailer Number must be 1 to 50 digits." }),
  LicensePlatePattern: z.string().regex(/^[A-Z0-9]{1,10}$/, { message: "License Plate must be 1-10 alphanumeric characters." }),
  LicenseNumberPattern: z.string().regex(/^[A-Z0-9]{1,15}$/, { message: "License Number must be 1-15 alphanumeric characters." }),
  VINPattern: z.string().regex(/^[A-Z0-9]{9,17}$/, { message: "VIN must be 9-17 alphanumeric characters." }),
  VINPatternStrict: z.string().regex(/^[A-Z0-9]{10,17}$/, { message: "VIN must be 10-17 alphanumeric characters." }),
  YearPattern: z.string({ invalid_type_error: "Year must be text." }).regex(/^[0-9]{4}$/, { message: "Year must be a 4-digit number." }),
  SCACPattern: z.string().regex(/^[A-Z]{4}$/, { message: "SCAC must be 4 uppercase letters." }),
  MCNumberPattern: z.string().regex(/^.{2,}$/, { message: "Invalid MC Number format." }),
  USDOTPattern: z.string({ invalid_type_error: "USDOT Number must be text." }).regex(/^[0-9]{7,8}$/, { message: "USDOT Number must be 7 to 8 digits." }),
  CountryCodeNumeric: z.string({ invalid_type_error: "Country Code must be text." }).regex(/^[0-9]{1,3}$/, { message: "Numeric Country Code must be 1-3 digits." }),
  LicenseStatePattern: z.string().regex(/^[A-Za-z\s]{2,50}$/, { message: "Invalid License State format." }),
  SealinkPattern: z.string().regex(/^[A-Z0-9]{1,20}$/, { message: "Sealink must be 1-20 alphanumeric characters." }),
  PasswordPattern: z.string().min(9).max(9).regex(/^[A-Z]{3}\d{5}\*$/, { message: "Password must be exactly 9 characters: 3 uppercase letters, 5 digits, and 1 asterisk (*)." }),
  SystemRolesPattern: z.string().regex(/^(?:\s*(?:Admin|CSR|Sales\sAgent|Mechanics)\s*)(?:,\s*(?:Admin|CSR|Sales\sAgent|Mechanics)\s*)*$/, { message: "Invalid System Role." }),
  OrganizationTypePattern: z.string().regex(/^(?:ALL|CUSTOMER|TERMINAL|WAREHOUSE|CONTAINERRETURN|CHASSISPICK|CHASSISTERMINATION)$/, { message: "Invalid Organization Type." }),
  CurrencyCodePattern: z.string().regex(/^[A-Z]{3}$/, { message: "Currency Code must be 3 uppercase letters." }),
  ChassisPattern20: z.string().regex(/^[0-9]{2,3}'$/, { message: "Chassis size must be in the format XX' or XXX'." }),
};

// Helper function to create lookup-enabled string field
const createLookupString = (minLength?: number, maxLength?: number, lookupId?: string, lookupField?: string) => {
  let schema = z.string();
  if (minLength) schema = schema.min(minLength);
  if (maxLength) schema = schema.max(maxLength);
  if (lookupId && lookupField) {
    (schema as any).lookupValidation = { lookupId, lookupField };
  }
  return schema;
};

// Helper function to create boolean that accepts Yes/No
const createYesNoBoolean = () => {
  return z.union([
    z.boolean(),
    z.string().transform((val) => {
      const lower = val.toLowerCase();
      if (lower === 'yes' || lower === 'y' || lower === 'true' || lower === '1' || lower === 't') return true;
      if (lower === 'no' || lower === 'n' || lower === 'false' || lower === '0' || lower === 'f') return false;
      throw new Error(`Invalid boolean value: ${val}. Expected: Yes, No, true, false, 1, 0, T, or F`);
    })
  ]);
};

// Helper function to create multi-event regex pattern
const createMultiEventPattern = () => {
  return /^(Enroute to Chassis|Arrived to Chassis|Enroute to Pick Container|Arrived at Pick Container|Enroute to Drop Container|Dropped|Enroute to Hook Container|Arrived to Hook Container|Enroute to Deliver Load|Arrived at Deliver Load|Enroute to Return Load|Arrived at Return Load|Enroute to Return Chassis|Arrived to Return Chassis|COMPLETED|PICKUP APT|DELIVERY APT|RETURN APT|READY TO RETURN|POD IN|POD OUT|Enroute to Lift Off|Arrived at Lift Off|Enroute to Lift On|Arrived at Lift On|Enroute to Stop Off|Arrived at Stop Off)(?:,\s*(Enroute to Chassis|Arrived to Chassis|Enroute to Pick Container|Arrived at Pick Container|Enroute to Drop Container|Dropped|Enroute to Hook Container|Arrived to Hook Container|Enroute to Deliver Load|Arrived at Deliver Load|Enroute to Return Load|Arrived at Return Load|Enroute to Return Chassis|Arrived to Return Chassis|COMPLETED|PICKUP APT|DELIVERY APT|RETURN APT|READY TO RETURN|POD IN|POD OUT|Enroute to Lift Off|Arrived at Lift Off|Enroute to Lift On|Arrived at Lift On|Enroute to Stop Off|Arrived at Stop Off))*$/;
};

// Helper function to create multi-event regex pattern for effective date based on
const createMultiEventPatternForEffectiveDateBasedOn = () => {
  return /^(CURRENT DATE|CREATED AT|MOVE START DATE|DEPARTED FROM CHASSIS|ARRIVED TO CHASSIS|ARRIVED AT PULL CONTAINER|DEPARTED FROM PULL CONTAINER|ARRIVED AT DELIVER LOAD|DEPARTED FROM DELIVER LOAD|ARRIVED AT DROP CONTAINER|DEPARTED FROM DROP CONTAINER|ARRIVED AT HOOK CONTAINER|DEPARTED FROM HOOK CONTAINER|ARRIVED AT RETURN CONTAINER|DEPARTED FROM RETURN CONTAINER|ARRIVED AT CHASSIS TERMINATION|DEPARTED FROM CHASSIS TERMINATION|ARRIVED AT STOP OFF|DEPARTED FROM STOP OFF|COMPLETED|PICKUP APT|DELIVERY APT|RETURN APT)(?:,\s*(CURRENT DATE|CREATED AT|MOVE START DATE|DEPARTED FROM CHASSIS|ARRIVED TO CHASSIS|ARRIVED AT PULL CONTAINER|DEPARTED FROM PULL CONTAINER|ARRIVED AT DELIVER LOAD|DEPARTED FROM DELIVER LOAD|ARRIVED AT DROP CONTAINER|DEPARTED FROM DROP CONTAINER|ARRIVED AT HOOK CONTAINER|DEPARTED FROM HOOK CONTAINER|ARRIVED AT RETURN CONTAINER|DEPARTED FROM RETURN CONTAINER|ARRIVED AT CHASSIS TERMINATION|DEPARTED FROM CHASSIS TERMINATION|ARRIVED AT STOP OFF|DEPARTED FROM STOP OFF|COMPLETED|PICKUP APT|DELIVERY APT|RETURN APT))*$/;
};


// Load Schema - Updated to match exportEntities.json exactly
const LoadSchema = z.object({
  Customer: createLookupString(2, 100, 'tmsCustomers', 'company_name'),
  'Load Type': Patterns.LoadTypePattern.max(50),
  'Pick Up Location': createLookupString(undefined, 200, 'tmsCustomers', 'company_name'),
  Container: z.string().max(20).optional(),
  'Delivery City/State': createLookupString(undefined, 100, 'tmsCustomers', 'company_name'),
  'Container Size': createLookupString(undefined, 10, 'containerSizes', 'name').optional(),
  'Container Type': createLookupString(undefined, 10, 'containerTypes', 'name').optional(),
  'Weight LBS': z.number().min(1).max(50).optional(),
  'Weight KGS': z.number().min(1).max(50).optional(),
  'Delivery Order': z.string().max(50).optional(),
  Owner: createLookupString(undefined, 100, 'containerOwners', 'name').optional(),
  'Booking #': z.string().max(50).optional(),
  'Master Bill Of Lading': z.string().max(50).optional(),
  'Container ETA': Patterns.DateMMDDYYYY.optional(),
  'Last Free Day': Patterns.DateMMDDYYYY.optional(),
  'Container Return': createLookupString(undefined, 200, 'tmsCustomers', 'company_name').optional(),
  'Hook Chassis Location': createLookupString(undefined, 200, 'tmsCustomers', 'company_name').optional(),
  'Terminate Chassis Location': createLookupString(undefined, 200, 'tmsCustomers', 'company_name').optional(),
  'Reference #': z.string().max(50).optional(),
  'Empty Date': Patterns.DateMMDDYYYY.optional(),
  'Date Returned': Patterns.DateMMDDYYYY.optional(),
  'Pick Up Apt From': Patterns.DateMMDDYYYY.optional(),
  'Delivery Apt From': Patterns.DateMMDDYYYY.optional(),
  ERD: Patterns.DateMMDDYYYY.optional(),
  'Per Diem Free Day': Patterns.DateMMDDYYYY.optional(),
  'Loaded Date': Patterns.DateMMDDYYYY.optional(),
  'Billing Date': Patterns.DateMMDDYYYY.optional(),
  'Chassis #': createLookupString(undefined, 20, 'chassis', 'chassisNo').optional(),
  'Chassis Owner': createLookupString(undefined, 100, 'chassisOwners', 'company_name').optional(),
  'Chassis Size': createLookupString(undefined, 10, 'chassisSizes', 'name').optional(),
  'Chassis Type': createLookupString(undefined, 10, 'chassisTypes', 'name').optional(),
  'Cut Off Date': Patterns.DateMMDDYYYY.optional(),
  'House Bill Of Lading': z.string().max(50).optional(),
  'Pick Up #': z.string().max(50).optional(),
  'Purchase Order #': z.string().max(50).optional(),
  'Seal #': z.string().max(20).optional(),
  'Shipment #': z.string().max(50).optional(),
  Temperature: z.number().optional(),
  Branch: createLookupString(undefined, 100, 'branches', 'name').optional(),
  'Vessel Name': z.string().max(100).optional(),
  Voyage: z.string().max(50).optional(),
  Commodity: createLookupString(undefined, 100, 'commodities', 'name').optional(),
  Pieces: z.number().optional(),
  Hazmat: createYesNoBoolean().optional(),
  Hot: createYesNoBoolean().optional(),
  Overweight: createYesNoBoolean().optional(),
  Routes: Patterns.RoutesPattern.max(100).optional(),
  Genset: createYesNoBoolean().optional(),
  Liquor: createYesNoBoolean().optional(),
  Overheight: createYesNoBoolean().optional(),
  'Street Turn': createYesNoBoolean().optional(),
  Scale: createYesNoBoolean().optional(),
});

// Carrier Schema - Updated to match exportEntities.json
const CarrierSchema = z.object({
  'Company Name': z.string().min(2).max(100),
  'Contact Name': z.string().min(2).max(100),
  Address: z.string().min(5).max(200),
  Country: Patterns.CountryCode,
  State: Patterns.USState,
  City: z.string().min(2).max(50),
  ZIP: Patterns.USZip,
  'Login Email Address': Patterns.Email,
  'Tender Email Address 1': Patterns.Email,
  'Tender Email Address 2': Patterns.Email.optional(),
  'Tender Email Address 3': Patterns.Email.optional(),
  'Phone Number': Patterns.PhoneFormatted,
  SCAC: Patterns.SCACPattern.optional(),
  'MC#': Patterns.MCNumberPattern.optional(),
  'USDOT Number': Patterns.USDOTPattern.optional(),
  'External ID': z.string().max(50).optional(),
  'Branch 1': createLookupString(undefined, 50, 'branches', 'name').optional(),
});

// Load Tariff Schema - Updated to match exportEntities.json
const LoadTariffSchema = z.object({
  'Tariff Name': z.string().min(2).max(100),
  'Effective Start Date': Patterns.DateSlashMMDDYYYY.optional(),
  'Effective End Date': Patterns.DateSlashMMDDYYYY.optional(),
  'Load Type': z.string().regex(/^(IMPORT|EXPORT|ROAD)(?:,\s*(IMPORT|EXPORT|ROAD))*$/),
  'Branch': createLookupString(undefined, 100, 'branches', 'name'),
  'Customer': createLookupString(2, 100, 'tmsCustomers', 'company_name'),
  'Pick Up Location': createLookupString(2, 100, 'tmsCustomers', 'company_name'),
  'Delivery Location': createLookupString(2, 100, 'tmsCustomers', 'company_name'),
  'Return Location': createLookupString(2, 100, 'tmsCustomers', 'company_name'),
  'Container Type': createLookupString(2, 10, 'containerTypes', 'name'),
  'Container Size': createLookupString(2, 10, 'containerSizes', 'name'),
  'SSL': createLookupString(2, 100, 'containerOwners', 'name'),
  'CSR': createLookupString(undefined, 100, 'CSR', 'name'),
  'Chassis Type': createLookupString(2, 10, 'chassisTypes', 'name'),
  'Chassis Size': createLookupString(2, 10, 'chassisSizes', 'name'),
  'Chassis Owner': createLookupString(2, 100, 'chassisOwners', 'name'),
  'Hazmat': Patterns.YesNo.optional(),
  'Hot': Patterns.YesNo.optional(),
  'Overweight': Patterns.YesNo.optional(),
  'Liquor': Patterns.YesNo.optional(),
  'Genset': Patterns.YesNo.optional(),
  'Scale': Patterns.YesNo.optional(),
  'Domestic': Patterns.YesNo.optional(),
  'EV': Patterns.YesNo.optional(),
  'Waste': Patterns.YesNo.optional(),
  'GDP': Patterns.YesNo.optional(),
  'Rail': Patterns.YesNo.optional(),
  'Street Turn': Patterns.YesNo.optional(),
  'OOG': Patterns.YesNo.optional(),
  'Bonded': Patterns.YesNo.optional(),
});

// Trailers Schema - Updated to match exportEntities.json
const TrailersSchema = z.object({
  'Trailer #': Patterns.TrailerNumberPattern,
  Year: Patterns.YearPattern.optional(),
  Make: z.string().max(50).optional(),
  Model: z.string().max(50).optional(),
  AID: Patterns.DateYYYYMMDD.optional(),
  ITD: Patterns.DateYYYYMMDD.optional(),
  VIN: Patterns.VINPattern.optional(),
  'Registration Expiration': Patterns.DateYYYYMMDD.optional(),
  'Inspection Expiration': Patterns.DateYYYYMMDD.optional(),
  'License Plate State': Patterns.USState.optional(),
  'License Plate #': Patterns.LicensePlatePattern.optional(),
  'HUT Expiration': Patterns.DateYYYYMMDD.optional(),
  'Trailer Type': Patterns.TrailerTypePattern.max(50).optional(),
  'Trailer Size': Patterns.TrailerSizePattern.optional(),
  Branch: createLookupString(undefined, 100, 'branches', 'name'),
});

// Truck Owner Schema - Updated to match exportEntities.json
const TruckOwnerSchema = z.object({
  'Company Name': z.string().min(2).max(100),
  Address: z.string().min(5).max(200),
  'DOT #': z.string().min(2).max(15).optional(),
  'MC #': Patterns.MCNumberPattern.optional(),
  'Main Contact Name': z.string().min(2).max(100).optional(),
  'Secondary Contact Name': z.string().min(2).max(100).optional(),
  Mobile: Patterns.PhoneFormatted.optional(),
  Email: Patterns.Email.optional(),
  'Tax ID/EIN #': z.string().min(2).max(15).optional(),
  SSN: z.string().min(2).max(15).optional(),
});

// Trucks Schema - Updated to match exportEntities.json
const TrucksSchema = z.object({
  'Equipment ID': Patterns.EquipmentIDPattern,
  'License State': Patterns.USState.optional(),
  'License Plate #': Patterns.LicensePlatePattern.optional(),
  Year: Patterns.YearPattern.optional(),
  Make: z.string().max(50).optional(),
  Model: z.string().max(50).optional(),
  AID: Patterns.DateYYYYMMDD.optional(),
  ITD: Patterns.DateYYYYMMDD.optional(),
  VIN: Patterns.VINPatternStrict.optional(),
  'Registration Expiration': Patterns.DateYYYYMMDD.optional(),
  'Inspection Expiration': Patterns.DateYYYYMMDD.optional(),
  'HUT Expiration': Patterns.DateYYYYMMDD.optional(),
  'Annual Inspection': Patterns.DateYYYYMMDD.optional(),
  'Bobtail Insurance': Patterns.DateYYYYMMDD.optional(),
  'Diesel Emission': Patterns.DateYYYYMMDD.optional(),
  'Truck Owner': createLookupString(undefined, 100, 'fleetOwners', 'company_name').optional(),
  Branch: createLookupString(undefined, 100, 'branches', 'name'),
});

// Users Schema - Updated to match exportEntities.json
const UsersSchema = z.object({
  'First Name*': z.string().min(2).max(50),
  'Last Name*': z.string().min(2).max(50),
  Phone: Patterns.PhoneFormatted.optional(),
  'Email*': Patterns.Email,
  'Password*': Patterns.PasswordPattern,
  'System Roles*': Patterns.SystemRolesPattern.max(200),
  'Terminal*': createLookupString(undefined, 100, 'branches', 'name'),
  'Custom Role': createLookupString(undefined, 100, 'getAllPermissionRoles', 'roleName').optional(),
});

// Charge Profile Schema - Updated to match exportEntities.json
const ChargeProfileSchema = z.object({
  'Charge Profile Name': z.string().min(2).max(100),
  'Charge Name': createLookupString(2, 100, 'chargeCodes', 'value').optional(),
  'Charge Description': z.string().max(500).optional(),
  'Unit of Measure':  z.string().regex(/\b(Per Kilograms|Per Pounds|Per Kilometers|Per Miles|Percentage|Per Day|Per Hour|Per Road Toll|Fixed|Per 15min|Per 30min|Per 45min|Radius Rate|Compounding Radius Rate|Per Move|Percentage By Leg|Percentage By Move|Per Hour Blocks)\b/i),
  'Effective date based on': z.string().regex(createMultiEventPatternForEffectiveDateBasedOn()).optional(),
  'Charge Effective Start Date': Patterns.DateSlashMMDDYYYY.optional(),
  'Charge Effective End Date': Patterns.DateSlashMMDDYYYY.optional(),
  'Auto Add': Patterns.YesNo.optional(),
  'Calculate From This': z.string().regex(createMultiEventPattern()),
  'Calculate To This': z.string().regex(createMultiEventPattern()),
  'Calculate In This Event': z.string().regex(createMultiEventPattern()),
  'Calculate For Exact Events': z.string().regex(createMultiEventPattern()).optional(),
  'Zip Code Rule (any in)': z.string().max(500).optional(),
  'Zip Code Rule (not in)': z.string().max(500).optional(),
  'Load Type Rule (any in)': z.string().regex(/^(IMPORT|EXPORT|ROAD)(?:,\s*(IMPORT|EXPORT|ROAD))*$/),
  'Load Type Rule (not in)': z.string().regex(/^(IMPORT|EXPORT|ROAD)(?:,\s*(IMPORT|EXPORT|ROAD))*$/),
  'City State Rule (any in)': z.string().max(500).optional(),
  'City State Rule (not in)': z.string().max(500).optional(),
  'Customer(any in)': createLookupString(undefined, 100, 'branches', 'name'),
  'Customer(not in)': createLookupString(undefined, 100, 'branches', 'name'),
  'Warehouse(any in)': createLookupString(undefined, 100, 'branches', 'name'),
  'Warehouse(not in)': createLookupString(undefined, 100, 'branches', 'name'),
  'Chassis Pick Up(any in)': createLookupString(undefined, 100, 'branches', 'name'),
  'Chassis Pick Up(not in)': createLookupString(undefined, 100, 'branches', 'name'),
  'Container Return(any in)': createLookupString(undefined, 100, 'branches', 'name'),
  'Container Return(not in)': createLookupString(undefined, 100, 'branches', 'name'),
  'Chassis Term(any in)': createLookupString(undefined, 100, 'branches', 'name'),
  'Chassis Term(not in)': createLookupString(undefined, 100, 'branches', 'name'),
  'Container Type(any in)': createLookupString(undefined, 100, 'containerTypes', 'name'),
  'Container Type(not in)': createLookupString(undefined, 100, 'containerTypes', 'name'),
  'Container Size(any in)': createLookupString(undefined, 100, 'containerSizes', 'name'),
  'Container Size(not in)': createLookupString(undefined, 100, 'containerSizes', 'name'),
  'Container Owner(any in)': createLookupString(undefined, 100, 'containerOwners', 'name'),
  'Container Owner(not in)': createLookupString(undefined, 100, 'containerOwners', 'name'),
  'Chassis Type(any in)': createLookupString(undefined, 100, 'chassisTypes', 'name'),
  'Chassis Type(not in)': createLookupString(undefined, 100, 'chassisTypes', 'name'),
  'Chassis Size(any in)': createLookupString(undefined, 100, 'chassisSizes', 'name'),
  'Chassis Size(not in)': createLookupString(undefined, 100, 'chassisSizes', 'name'),
  'Chassis Owner(any in)': createLookupString(undefined, 100, 'chassisOwners', 'name'),
  'Chassis Owner(not in)': createLookupString(undefined, 100, 'chassisOwners', 'name'),
  'Branch(any in)': createLookupString(undefined, 100, 'branches', 'name'),
  'Branch(not in)': createLookupString(undefined, 100, 'branches', 'name'),
  'Commodity(any in)': createLookupString(undefined, 100, 'commodities', 'name'),
  'Commodity(not in)': createLookupString(undefined, 100, 'commodities', 'name'),
  'Hot(any in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'Hot(not in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'Hazmat(any in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'Hazmat(not in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'Temperature(any in)': z.string().max(500).optional(),
  'Temperature(not in)': z.string().max(500).optional(),
  'Reefer(any in)': z.number().optional(),
  'Reefer(not in)': z.number().optional(),
  'Liquor(any in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'Liquor(not in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'City-State(any in)': z.string().max(500).optional(),
  'City-State(not in)': z.string().max(500).optional(),
  'State(any in)': Patterns.USState,
  'State(not in)': Patterns.USState,
  'Delivery Day(any in)': z.string().regex(/^(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday)(?:,\s*(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday))*$/),
  'Delivery Day(not in)': z.string().regex(/^(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday)(?:,\s*(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday))*$/),
  'Delivery Time(any in)': z.string().regex(/^([01]?[0-9]|2[0-3]):[0-5][0-9]$/),
  'Delivery Time(not in)': z.string().regex(/^([01]?[0-9]|2[0-3]):[0-5][0-9]$/),
  'City Groups(any in)': createLookupString(undefined, 100, 'cityGroups', 'name'),
  'City Groups(not in)': createLookupString(undefined, 100, 'cityGroups', 'name'),
  'Overweight(any in)': z.string().regex(/^(Yes|No)$/),
  'Overweight(not in)': z.string().regex(/^(Yes|No)$/),
  'Overheight(any in)': z.string().regex(/^(Yes|No)$/),
  'Overheight(not in)': z.string().regex(/^(Yes|No)$/),
  'Drop Location(any in)': createLookupString(undefined, 100, 'branches', 'name'),
  'Drop Location(not in)': createLookupString(undefined, 100, 'branches', 'name'),
  'Dropped(any in)': z.string().regex(/^(After Delivery|Before Delivery)(?:,\s*(After Delivery|Before Delivery))*$/),
  'Dropped(not in)': z.string().regex(/^(After Delivery|Before Delivery)(?:,\s*(After Delivery|Before Delivery))*$/),
  'Genset(any in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'Genset(not in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'CSR(any in)': createLookupString(undefined, 100, 'CSR', 'name'),
  'CSR(not in)': createLookupString(undefined, 100, 'CSR', 'name'),
  'Stop Off(any in)': z.string().max(500).optional(),
  'Stop Off(not in)': z.string().max(500).optional(),
  'Delivery Country(any in)': z.string().regex(/^[A-Z]{2}(?:,\s*[A-Z]{2})*$/),
  'Delivery Country(not in)': z.string().regex(/^[A-Z]{2}(?:,\s*[A-Z]{2})*$/),
  'Postal/Zip Code Groups(any in)': createLookupString(undefined, 100, 'zipCodeGroups', 'name'),
  'Postal/Zip Code Groups(not in)': createLookupString(undefined, 100, 'zipCodeGroups', 'name'),
  'Street Turn Type(any in)': z.string().regex(/^(Commercial|Operational)(?:,\s*(Commercial|Operational))*$/),
  'Street Turn Type(not in)': z.string().regex(/^(Commercial|Operational)(?:,\s*(Commercial|Operational))*$/),
  'Trip Type(any in)': z.string().regex(/^(Commercial|Operational)(?:,\s*(Commercial|Operational))*$/),
  'Trip Type(not in)': z.string().regex(/^(Commercial|Operational)(?:,\s*(Commercial|Operational))*$/),
  'Scale(any in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'Scale(not in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'Dual Transaction(any in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'Dual Transaction(not in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'Street Turn(any in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'Street Turn(not in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'EV(any in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'EV(not in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'Bonded(any in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'Bonded(not in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'OOG(any in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'OOG(not in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'Minimum Amount': z.number().optional(),
  'Free Units': z.number().optional(),
  Amount: z.number().optional(),
  'Rate Type': z.string().regex(/^Fixed|Per Unit$/),
  'Start Distance': z.number().optional(),
  'End Distance': z.number().optional(),
  'If Event': z.string().regex(/^(Pick Up Container|Deliver Container|Return Container|Drop Container|Stop Off|Terminate Chassis|Completed|Hook Container|Lift Off|Lift On|Deliver Load - Drop & Hook|Hook Chassis|Drop Chassis)$/),
  'Event Location': createLookupString(undefined, 100, 'tmsCustomers', 'company_name'),
  'Event Time': z.string().regex(/^Arrived|Departure$/),
  'Event Location Rules': z.string().max(1000).optional(),
  'From Legs': z.string().regex(/^(Pick Up Container|Deliver Container|Return Container|Drop Container|Stop Off|Terminate Chassis|Completed|Hook Container|Lift Off|Lift On|Deliver Load - Drop & Hook|Hook Chassis|Drop Chassis)$/),
  'To Legs': z.string().regex(/^(Pick Up Container|Deliver Container|Return Container|Drop Container|Stop Off|Terminate Chassis|Completed|Hook Container|Lift Off|Lift On|Deliver Load - Drop & Hook|Hook Chassis|Drop Chassis)$/),
  'From Leg Event Location': createLookupString(undefined, 100, 'tmsCustomers', 'company_name'),
  'To Leg Event Location': createLookupString(undefined, 100, 'tmsCustomers', 'company_name'),
});

// Chassis Owner Schema - Updated to match exportEntities.json
const ChassisOwnerSchema = z.object({
  'Company Name': z.string().min(2).max(100),
  'Contact Name': z.string().min(2).max(100),
  Phone: Patterns.PhoneFormatted,
  Address: z.string().min(5).max(200),
  City: z.string().min(2).max(50),
  State: z.string().min(2).max(50),
  'Zip Code': Patterns.USZip,
  Country: z.string().min(2).max(100),
});

// Chassis Schema - Updated to match exportEntities.json
const ChassisSchema = z.object({
  'Chassis #': Patterns.ChassisNumberPattern,
  'Chassis Type': createLookupString(2, 50, 'chassisTypes', 'name'),
  'Chassis Size': z.string().regex(/^[0-9]{2,3}'$/).and(createLookupString(undefined, undefined, 'chassisSizes', 'name')),
  'Chassis Owner': createLookupString(2, 100, 'chassisOwners', 'company_name'),
  Year: Patterns.YearPattern.optional(),
  Make: z.string().max(50).optional(),
  Model: z.string().max(50).optional(),
  'Annual Inspection Date': Patterns.DateYYYYMMDD.optional(),
  ITD: Patterns.DateYYYYMMDD.optional(),
  Branch: createLookupString(undefined, 100, 'branches', 'name'),
  'License State': Patterns.ChassisLicensePattern.optional(),
  'License Number': Patterns.LicenseNumberPattern.optional(),
  VIN: Patterns.VINPattern.optional(),
  Registration: Patterns.DateYYYYMMDD.optional(),
  Inspection: Patterns.DateYYYYMMDD.optional(),
  Insurance: Patterns.DateYYYYMMDD.optional(),
});

// People Schema - Updated to match exportEntities.json
const PeopleSchema = z.object({
  Email: Patterns.Email,
  'First Name': z.string().min(2).max(50),
  'Last Name': z.string().min(2).max(50),
  Mobile: Patterns.PhoneFormatted,
  'Customer ID': createLookupString(2, 100, 'tmsCustomers', 'company_name'),
  Password: Patterns.PasswordPattern,
  'Loads Permission': z.boolean().optional(),
  'Dropped Containers Permission': z.boolean().optional(),
  'Account Payable Permission': z.boolean().optional(),
  'Info Permission': z.boolean().optional(),
  'Billing Permission': z.boolean().optional(),
  'Documents Permission': z.boolean().optional(),
  'Upload Documents Permission': z.boolean().optional(),
  'Payments Permission': z.boolean().optional(),
  'Tracking Permission': z.boolean().optional(),
  'Service Messaging Permission': z.boolean().optional(),
  'Summary Permission': z.boolean().optional(),
  'Shipment Tracking Permission': z.boolean().optional(),
  'Customer Permission': z.boolean().optional(),
});

// Organization Schema - Updated to match exportEntities.json
const OrganizationSchema = z.object({
  'Company Name': z.string().min(2).max(100),
  Address: z.string().min(5).max(200),
  City: z.string().min(2).max(50),
  State: z.string().min(2), // No max limit specified in exportEntities.json
  Country: Patterns.CountryCode,
  'Zip Code': Patterns.USZipExtended,
  'Main Contact Name': z.string().min(2).max(100).optional(),
  'Secondary Contact Name': z.string().min(2).max(100).optional(),
  'Secondary Phone': Patterns.PhoneFormatted.optional(),
  Mobile: Patterns.PhoneFormatted.optional(),
  Email: Patterns.Email.optional(),
  'Billing Email': Patterns.Email.optional(),
  Password: Patterns.PasswordPattern.optional(),
  'Payment Terms Method': z.string().max(50).optional(),
  'Payment Terms + Days': z.number().optional(),
  'Credit Limit': z.number().optional(),
  Branch: createLookupString(undefined, undefined, 'branches', 'name'),
  'Organization Type': Patterns.OrganizationTypePattern,
  'Receiver email': Patterns.Email.optional(),
  'Mc number': Patterns.MCNumberPattern.optional(),
  'Fleet customer': createLookupString(undefined, undefined, 'getTMSFleetCustomers', 'company_name').optional(),
  'Pay type': z.string().max(50).optional(),
  'Currency Type': z.string().regex(/^[A-Z]{3}$/).and(createLookupString(undefined, undefined, 'currencies', 'currencyCode')).optional(),
  'External ID': z.string().regex(/^[A-Za-z0-9&+]+$/).optional(),
  'Latitude': z.number().optional(),
  'Longitude': z.number().optional()
});

// Driver Charge Profile Schema - Updated to match exportEntities.json
const DriverChargeProfileSchema = z.object({
  'Charge Profile Name': z.string().min(2).max(100),
  'Charge Name': createLookupString(2, 100, 'chargeCodes', 'value').optional(),
  'Charge Description': z.string().max(500).optional(),
  'Unit of Measure': z.string().regex(/\b(Per Kilograms|Per Pounds|Per Kilometers|Per Miles|Percentage|Per Day|Per Hour|Per Road Toll|Fixed|Per 15min|Per 30min|Per 45min|Radius Rate|Compounding Radius Rate|Per Move|Percentage By Leg|Percentage By Move|Per Hour Blocks)\b/i),
  'Effective date based on': z.string().regex(createMultiEventPatternForEffectiveDateBasedOn()).optional(),
  'Charge Effective Start Date': Patterns.DateSlashMMDDYYYY.optional(),
  'Charge Effective End Date': Patterns.DateSlashMMDDYYYY.optional(),
  'Auto Add': Patterns.YesNo.optional(),
  'Calculate From This': z.string().regex(createMultiEventPattern()),
  'Calculate To This': z.string().regex(createMultiEventPattern()),
  'Calculate In This Event': z.string().regex(createMultiEventPattern()),
  'Calculate For Exact Events': z.string().regex(createMultiEventPattern()).optional(),
  'Zip Code Rule (any in)': z.string().max(500).optional(),
  'Zip Code Rule (not in)': z.string().max(500).optional(),
  'Load Type Rule (any in)': z.string().regex(/^(IMPORT|EXPORT|ROAD)(?:,\s*(IMPORT|EXPORT|ROAD))*$/),
  'Load Type Rule (not in)': z.string().regex(/^(IMPORT|EXPORT|ROAD)(?:,\s*(IMPORT|EXPORT|ROAD))*$/),
  'City State Rule (any in)': z.string().max(500).optional(),
  'City State Rule (not in)': z.string().max(500).optional(),
  'Customer(any in)': createLookupString(undefined, 100, 'branches', 'name'),
  'Customer(not in)': createLookupString(undefined, 100, 'branches', 'name'),
  'Warehouse(any in)': createLookupString(undefined, 100, 'branches', 'name'),
  'Warehouse(not in)': createLookupString(undefined, 100, 'branches', 'name'),
  'Chassis Pick Up(any in)': createLookupString(undefined, 100, 'branches', 'name'),
  'Chassis Pick Up(not in)': createLookupString(undefined, 100, 'branches', 'name'),
  'Container Return(any in)': createLookupString(undefined, 100, 'branches', 'name'),
  'Container Return(not in)': createLookupString(undefined, 100, 'branches', 'name'),
  'Chassis Term(any in)': createLookupString(undefined, 100, 'branches', 'name'),
  'Chassis Term(not in)': createLookupString(undefined, 100, 'branches', 'name'),
  'Container Type(any in)': createLookupString(undefined, 100, 'containerTypes', 'name'),
  'Container Type(not in)': createLookupString(undefined, 100, 'containerTypes', 'name'),
  'Container Size(any in)': createLookupString(undefined, 100, 'containerSizes', 'name'),
  'Container Size(not in)': createLookupString(undefined, 100, 'containerSizes', 'name'),
  'Container Owner(any in)': createLookupString(undefined, 100, 'containerOwners', 'name'),
  'Container Owner(not in)': createLookupString(undefined, 100, 'containerOwners', 'name'),
  'Chassis Type(any in)': createLookupString(undefined, 100, 'chassisTypes', 'name'),
  'Chassis Type(not in)': createLookupString(undefined, 100, 'chassisTypes', 'name'),
  'Chassis Size(any in)': createLookupString(undefined, 100, 'chassisSizes', 'name'),
  'Chassis Size(not in)': createLookupString(undefined, 100, 'chassisSizes', 'name'),
  'Chassis Owner(any in)': createLookupString(undefined, 100, 'chassisOwners', 'name'),
  'Chassis Owner(not in)': createLookupString(undefined, 100, 'chassisOwners', 'name'),
  'Branch(any in)': createLookupString(undefined, 100, 'branches', 'name'),
  'Branch(not in)': createLookupString(undefined, 100, 'branches', 'name'),
  'Commodity(any in)': createLookupString(undefined, 100, 'commodities', 'name'),
  'Commodity(not in)': createLookupString(undefined, 100, 'commodities', 'name'),
  'Hot(any in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'Hot(not in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'Hazmat(any in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'Hazmat(not in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'Temperature(any in)': z.string().max(500).optional(),
  'Temperature(not in)': z.string().max(500).optional(),
  'Reefer(any in)': z.number().optional(),
  'Reefer(not in)': z.number().optional(),
  'Liquor(any in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'Liquor(not in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'City-State(any in)': z.string().max(500).optional(),
  'City-State(not in)': z.string().max(500).optional(),
  'State(any in)': Patterns.USState,
  'State(not in)': Patterns.USState,
  'Delivery Day(any in)': z.string().regex(/^(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday)(?:,\s*(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday))*$/),
  'Delivery Day(not in)': z.string().regex(/^(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday)(?:,\s*(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday))*$/),
  'Delivery Time(any in)': z.string().regex(/^([01]?[0-9]|2[0-3]):[0-5][0-9]$/),
  'Delivery Time(not in)': z.string().regex(/^([01]?[0-9]|2[0-3]):[0-5][0-9]$/),
  'City Groups(any in)': createLookupString(undefined, 100, 'cityGroups', 'name'),
  'City Groups(not in)': createLookupString(undefined, 100, 'cityGroups', 'name'),
  'Overweight(any in)': z.string().regex(/^(Yes|No)$/),
  'Overweight(not in)': z.string().regex(/^(Yes|No)$/),
  'Overheight(any in)': z.string().regex(/^(Yes|No)$/),
  'Overheight(not in)': z.string().regex(/^(Yes|No)$/),
  'Drop Location(any in)': createLookupString(undefined, 100, 'branches', 'name'),
  'Drop Location(not in)': createLookupString(undefined, 100, 'branches', 'name'),
  'Dropped(any in)': z.string().regex(/^(After Delivery|Before Delivery)(?:,\s*(After Delivery|Before Delivery))*$/),
  'Dropped(not in)': z.string().regex(/^(After Delivery|Before Delivery)(?:,\s*(After Delivery|Before Delivery))*$/),
  'Genset(any in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'Genset(not in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'CSR(any in)': createLookupString(undefined, 100, 'CSR', 'name'),
  'CSR(not in)': createLookupString(undefined, 100, 'CSR', 'name'),
  'Stop Off(any in)': z.string().max(500).optional(),
  'Stop Off(not in)': z.string().max(500).optional(),
  'Delivery Country(any in)': z.string().regex(/^[A-Z]{2}(?:,\s*[A-Z]{2})*$/),
  'Delivery Country(not in)': z.string().regex(/^[A-Z]{2}(?:,\s*[A-Z]{2})*$/),
  'Postal/Zip Code Groups(any in)': createLookupString(undefined, 100, 'zipCodeGroups', 'name'),
  'Postal/Zip Code Groups(not in)': createLookupString(undefined, 100, 'zipCodeGroups', 'name'),
  'Street Turn Type(any in)': z.string().regex(/^(Commercial|Operational)(?:,\s*(Commercial|Operational))*$/),
  'Street Turn Type(not in)': z.string().regex(/^(Commercial|Operational)(?:,\s*(Commercial|Operational))*$/),
  'Trip Type(any in)': z.string().regex(/^(Commercial|Operational)(?:,\s*(Commercial|Operational))*$/),
  'Trip Type(not in)': z.string().regex(/^(Commercial|Operational)(?:,\s*(Commercial|Operational))*$/),
  'Scale(any in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'Scale(not in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'Dual Transaction(any in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'Dual Transaction(not in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'Street Turn(any in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'Street Turn(not in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'EV(any in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'EV(not in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'Bonded(any in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'Bonded(not in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'OOG(any in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'OOG(not in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'Minimum Amount': z.number().optional(),
  'Free Units': z.number().optional(),
  Amount: z.number().optional(),
  'Rate Type': z.string().regex(/^Fixed|Per Unit$/),
  'Start Distance': z.number().optional(),
  'End Distance': z.number().optional(),
  'If Event': z.string().regex(/^(Pick Up Container|Deliver Container|Return Container|Drop Container|Stop Off|Terminate Chassis|Completed|Hook Container|Lift Off|Lift On|Deliver Load - Drop & Hook|Hook Chassis|Drop Chassis)$/),
  'Event Location': createLookupString(undefined, 100, 'tmsCustomers', 'company_name'),
  'Event Time': z.string().regex(/^Arrived|Departure$/),
  'Event Location Rules': z.string().max(1000).optional(),
  'Driver Group': createLookupString(undefined, 100, 'driverGroups', 'name'),
  'From Legs': z.string().regex(/^(Pick Up Container|Deliver Container|Return Container|Drop Container|Stop Off|Terminate Chassis|Completed|Hook Container|Lift Off|Lift On|Deliver Load - Drop & Hook|Hook Chassis|Drop Chassis)$/),
  'To Legs': z.string().regex(/^(Pick Up Container|Deliver Container|Return Container|Drop Container|Stop Off|Terminate Chassis|Completed|Hook Container|Lift Off|Lift On|Deliver Load - Drop & Hook|Hook Chassis|Drop Chassis)$/),
  'From Leg Event Location': createLookupString(undefined, 100, 'tmsCustomers', 'company_name'),
  'To Leg Event Location': createLookupString(undefined, 100, 'tmsCustomers', 'company_name'),
});

// Driver Tariff Schema - Updated to match exportEntities.json
const DriverTariffSchema = z.object({
  'Driver Tariff Name': z.string().min(2).max(100),
  'Effective Start Date': Patterns.DateSlashMMDDYYYY.optional(),
  'Effective End Date': Patterns.DateSlashMMDDYYYY.optional(),
  'Load Type': z.string().regex(/^(IMPORT|EXPORT|ROAD)(?:,\s*(IMPORT|EXPORT|ROAD))*$/),
  'Branch': createLookupString(undefined, 100, 'branches', 'name'),
  'Customer': createLookupString(2, 100, 'tmsCustomers', 'company_name'),
  'Pick Up Location': createLookupString(2, 100, 'tmsCustomers', 'company_name'),
  'Delivery Location': createLookupString(2, 100, 'tmsCustomers', 'company_name'),
  'Return Location': createLookupString(2, 100, 'tmsCustomers', 'company_name'),
  'Container Type': createLookupString(2, 10, 'containerTypes', 'name'),
  'Container Size': createLookupString(2, 10, 'containerSizes', 'name'),
  'SSL': createLookupString(2, 100, 'containerOwners', 'name'),
  'CSR': createLookupString(undefined, 100, 'CSR', 'name'),
  'Chassis Type': createLookupString(2, 10, 'chassisTypes', 'name'),
  'Chassis Size': createLookupString(2, 10, 'chassisSizes', 'name'),
  'Chassis Owner': createLookupString(2, 100, 'chassisOwners', 'name'),
  'Hazmat': Patterns.YesNo.optional(),
  'Hot': Patterns.YesNo.optional(),
  'Overweight': Patterns.YesNo.optional(),
  'Liquor': Patterns.YesNo.optional(),
  'Genset': Patterns.YesNo.optional(),
  'Scale': Patterns.YesNo.optional(),
  'Domestic': Patterns.YesNo.optional(),
  'EV': Patterns.YesNo.optional(),
  'Waste': Patterns.YesNo.optional(),
  'GDP': Patterns.YesNo.optional(),
  'Rail': Patterns.YesNo.optional(),
  'Street Turn': Patterns.YesNo.optional(),
  'OOG': Patterns.YesNo.optional(),
  'Bonded': Patterns.YesNo.optional(),
  'Use Tariff for combined trips': Patterns.YesNo.optional(),
});

// Drivers Schema - Updated to match exportEntities.json
const DriversSchema = z.object({
  'First Name': z.string().min(2).max(50),
  'Last Name': z.string().min(2).max(50),
  Email: Patterns.Email.min(7).max(50),
  Phone: Patterns.PhoneFormatted,
  Password: Patterns.PasswordPattern,
  Username: Patterns.Username.min(3).max(50),
  'Truck Number': createLookupString(undefined, 50, 'trucks', 'equipmentID').optional(),
  'Country Code': Patterns.CountryCodeNumeric.optional(),
  'License State': Patterns.LicenseStatePattern.optional(),
  'License Number': Patterns.LicenseNumberPattern.optional(),
  'Sealink #': Patterns.SealinkPattern.optional(),
  'Emergency Contact Name': z.string().max(100).optional(),
  'Emergency Relation': z.string().max(50).optional(),
  'Emergency Contact Number': Patterns.Phone10.optional(),
  'Billing Email': Patterns.Email.optional(),
  'Profile Type': z.array(z.string()).optional(), // Lookup to driverProfileTypes
  'License Expiration': Patterns.DateYYYYMMDD.optional(),
  'Date of Birth': Patterns.DateYYYYMMDD.optional(),
  'Date of Hire': Patterns.DateYYYYMMDD.optional(),
  'Medical Expiration': Patterns.DateYYYYMMDD.optional(),
  'Twic Expiration': Patterns.DateYYYYMMDD.optional(),
  'Sea Link Expiration': Patterns.DateYYYYMMDD.optional(),
  Branch: createLookupString(undefined, 100, 'branches', 'name').optional(),
  'External Id': z.string().regex(/^[0-9]+$/).optional(),
  Hazmat: createYesNoBoolean().optional(),
  'Home Branch Time Zone': createLookupString(undefined, 100, 'timezoneList', 'type').optional(),
});

// Carrier Charge Profile Schema - Extends Charge Profile Schema
const CarrierChargeProfileSchema = z.object({
  'Charge Profile Name': z.string().min(2).max(100),
  'Charge Name': createLookupString(2, 100, 'chargeCodes', 'value').optional(),
  'Charge Description': z.string().max(500).optional(),
  'Unit of Measure': z.string().regex(/\b(Per Kilograms|Per Pounds|Per Kilometers|Per Miles|Percentage|Per Day|Per Hour|Per Road Toll|Fixed|Per 15min|Per 30min|Per 45min|Radius Rate|Compounding Radius Rate|Per Move|Percentage By Leg|Percentage By Move|Per Hour Blocks)\b/i),
  'Effective date based on': z.string().regex(createMultiEventPatternForEffectiveDateBasedOn()).optional(),
  'Charge Effective Start Date': Patterns.DateSlashMMDDYYYY.optional(),
  'Charge Effective End Date': Patterns.DateSlashMMDDYYYY.optional(),
  'Auto Add': Patterns.YesNo.optional(),
  'Calculate From This': z.string().regex(createMultiEventPattern()),
  'Calculate To This': z.string().regex(createMultiEventPattern()),
  'Calculate In This Event': z.string().regex(createMultiEventPattern()),
  'Calculate For Exact Events': z.string().regex(createMultiEventPattern()).optional(),
  'Zip Code Rule (any in)': z.string().max(500).optional(),
  'Zip Code Rule (not in)': z.string().max(500).optional(),
  'Load Type Rule (any in)': z.string().regex(/^(IMPORT|EXPORT|ROAD)(?:,\s*(IMPORT|EXPORT|ROAD))*$/),
  'Load Type Rule (not in)': z.string().regex(/^(IMPORT|EXPORT|ROAD)(?:,\s*(IMPORT|EXPORT|ROAD))*$/),
  'City State Rule (any in)': z.string().max(500).optional(),
  'City State Rule (not in)': z.string().max(500).optional(),
  'Customer(any in)': createLookupString(undefined, 100, 'branches', 'name'),
  'Customer(not in)': createLookupString(undefined, 100, 'branches', 'name'),
  'Warehouse(any in)': createLookupString(undefined, 100, 'branches', 'name'),
  'Warehouse(not in)': createLookupString(undefined, 100, 'branches', 'name'),
  'Chassis Pick Up(any in)': createLookupString(undefined, 100, 'branches', 'name'),
  'Chassis Pick Up(not in)': createLookupString(undefined, 100, 'branches', 'name'),
  'Container Return(any in)': createLookupString(undefined, 100, 'branches', 'name'),
  'Container Return(not in)': createLookupString(undefined, 100, 'branches', 'name'),
  'Chassis Term(any in)': createLookupString(undefined, 100, 'branches', 'name'),
  'Chassis Term(not in)': createLookupString(undefined, 100, 'branches', 'name'),
  'Container Type(any in)': createLookupString(undefined, 100, 'containerTypes', 'name'),
  'Container Type(not in)': createLookupString(undefined, 100, 'containerTypes', 'name'),
  'Container Size(any in)': createLookupString(undefined, 100, 'containerSizes', 'name'),
  'Container Size(not in)': createLookupString(undefined, 100, 'containerSizes', 'name'),
  'Container Owner(any in)': createLookupString(undefined, 100, 'containerOwners', 'name'),
  'Container Owner(not in)': createLookupString(undefined, 100, 'containerOwners', 'name'),
  'Chassis Type(any in)': createLookupString(undefined, 100, 'chassisTypes', 'name'),
  'Chassis Type(not in)': createLookupString(undefined, 100, 'chassisTypes', 'name'),
  'Chassis Size(any in)': createLookupString(undefined, 100, 'chassisSizes', 'name'),
  'Chassis Size(not in)': createLookupString(undefined, 100, 'chassisSizes', 'name'),
  'Chassis Owner(any in)': createLookupString(undefined, 100, 'chassisOwners', 'name'),
  'Chassis Owner(not in)': createLookupString(undefined, 100, 'chassisOwners', 'name'),
  'Branch(any in)': createLookupString(undefined, 100, 'branches', 'name'),
  'Branch(not in)': createLookupString(undefined, 100, 'branches', 'name'),
  'Commodity(any in)': createLookupString(undefined, 100, 'commodities', 'name'),
  'Commodity(not in)': createLookupString(undefined, 100, 'commodities', 'name'),
  'Hot(any in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'Hot(not in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'Hazmat(any in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'Hazmat(not in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'Temperature(any in)': z.string().max(500).optional(),
  'Temperature(not in)': z.string().max(500).optional(),
  'Reefer(any in)': z.number().optional(),
  'Reefer(not in)': z.number().optional(),
  'Liquor(any in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'Liquor(not in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'City-State(any in)': z.string().max(500).optional(),
  'City-State(not in)': z.string().max(500).optional(),
  'State(any in)': Patterns.USState,
  'State(not in)': Patterns.USState,
  'Delivery Day(any in)': z.string().regex(/^(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday)(?:,\s*(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday))*$/),
  'Delivery Day(not in)': z.string().regex(/^(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday)(?:,\s*(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday))*$/),
  'Delivery Time(any in)': z.string().regex(/^([01]?[0-9]|2[0-3]):[0-5][0-9]$/),
  'Delivery Time(not in)': z.string().regex(/^([01]?[0-9]|2[0-3]):[0-5][0-9]$/),
  'City Groups(any in)': createLookupString(undefined, 100, 'cityGroups', 'name'),
  'City Groups(not in)': createLookupString(undefined, 100, 'cityGroups', 'name'),
  'Overweight(any in)': z.string().regex(/^(Yes|No)$/),
  'Overweight(not in)': z.string().regex(/^(Yes|No)$/),
  'Overheight(any in)': z.string().regex(/^(Yes|No)$/),
  'Overheight(not in)': z.string().regex(/^(Yes|No)$/),
  'Drop Location(any in)': createLookupString(undefined, 100, 'branches', 'name'),
  'Drop Location(not in)': createLookupString(undefined, 100, 'branches', 'name'),
  'Dropped(any in)': z.string().regex(/^(After Delivery|Before Delivery)(?:,\s*(After Delivery|Before Delivery))*$/),
  'Dropped(not in)': z.string().regex(/^(After Delivery|Before Delivery)(?:,\s*(After Delivery|Before Delivery))*$/),
  'Genset(any in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'Genset(not in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'CSR(any in)': createLookupString(undefined, 100, 'CSR', 'name'),
  'CSR(not in)': createLookupString(undefined, 100, 'CSR', 'name'),
  'Stop Off(any in)': z.string().max(500).optional(),
  'Stop Off(not in)': z.string().max(500).optional(),
  'Delivery Country(any in)': z.string().regex(/^[A-Z]{2}(?:,\s*[A-Z]{2})*$/),
  'Delivery Country(not in)': z.string().regex(/^[A-Z]{2}(?:,\s*[A-Z]{2})*$/),
  'Postal/Zip Code Groups(any in)': createLookupString(undefined, 100, 'zipCodeGroups', 'name'),
  'Postal/Zip Code Groups(not in)': createLookupString(undefined, 100, 'zipCodeGroups', 'name'),
  'Street Turn Type(any in)': z.string().regex(/^(Commercial|Operational)(?:,\s*(Commercial|Operational))*$/),
  'Street Turn Type(not in)': z.string().regex(/^(Commercial|Operational)(?:,\s*(Commercial|Operational))*$/),
  'Trip Type(any in)': z.string().regex(/^(Commercial|Operational)(?:,\s*(Commercial|Operational))*$/),
  'Trip Type(not in)': z.string().regex(/^(Commercial|Operational)(?:,\s*(Commercial|Operational))*$/),
  'Scale(any in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'Scale(not in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'Dual Transaction(any in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'Dual Transaction(not in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'Street Turn(any in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'Street Turn(not in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'EV(any in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'EV(not in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'Bonded(any in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'Bonded(not in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'OOG(any in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'OOG(not in)': z.string().regex(/^(Yes|No)(?:,\s*(Yes|No))*$/),
  'Minimum Amount': z.number().optional(),
  'Free Units': z.number().optional(),
  Amount: z.number().optional(),
  'Rate Type': z.string().regex(/^Fixed|Per Unit$/),
  'Start Distance': z.number().optional(),
  'End Distance': z.number().optional(),
  'If Event': z.string().regex(/^(Pick Up Container|Deliver Container|Return Container|Drop Container|Stop Off|Terminate Chassis|Completed|Hook Container|Lift Off|Lift On|Deliver Load - Drop & Hook|Hook Chassis|Drop Chassis)$/),
  'Event Location': createLookupString(undefined, 100, 'tmsCustomers', 'company_name'),
  'Event Time': z.string().regex(/^Arrived|Departure$/),
  'Event Location Rules': z.string().max(1000).optional(),
  'Carrier Group': createLookupString(undefined, 100, 'carrierGroups', 'name'),
  'From Legs': z.string().regex(/^(Pick Up Container|Deliver Container|Return Container|Drop Container|Stop Off|Terminate Chassis|Completed|Hook Container|Lift Off|Lift On|Deliver Load - Drop & Hook|Hook Chassis|Drop Chassis)$/),
  'To Legs': z.string().regex(/^(Pick Up Container|Deliver Container|Return Container|Drop Container|Stop Off|Terminate Chassis|Completed|Hook Container|Lift Off|Lift On|Deliver Load - Drop & Hook|Hook Chassis|Drop Chassis)$/),
  'From Leg Event Location': createLookupString(undefined, 100, 'tmsCustomers', 'company_name'),
  'To Leg Event Location': createLookupString(undefined, 100, 'tmsCustomers', 'company_name'),
});

// Carrier Tariff Schema - Updated to match exportEntities.json
const CarrierTariffSchema = z.object({
  'Tariff Name': z.string().min(2).max(100),
  'Effective Start Date': Patterns.DateSlashMMDDYYYY.optional(),
  'Effective End Date': Patterns.DateSlashMMDDYYYY.optional(),
  'Load Type': z.string().regex(/^(IMPORT|EXPORT|ROAD)(?:,\s*(IMPORT|EXPORT|ROAD))*$/),
  'Branch': createLookupString(undefined, 100, 'branches', 'name'),
  'Customer': createLookupString(2, 100, 'tmsCustomers', 'company_name'),
  'Pick Up Location': createLookupString(2, 100, 'tmsCustomers', 'company_name'),
  'Delivery Location': createLookupString(2, 100, 'tmsCustomers', 'company_name'),
  'Return Location': createLookupString(2, 100, 'tmsCustomers', 'company_name'),
  'Container Type': createLookupString(2, 10, 'containerTypes', 'name'),
  'Container Size': createLookupString(2, 10, 'containerSizes', 'name'),
  'SSL': createLookupString(2, 100, 'containerOwners', 'name'),
  'CSR': createLookupString(undefined, 100, 'CSR', 'name'),
  'Chassis Type': createLookupString(2, 10, 'chassisTypes', 'name'),
  'Chassis Size': createLookupString(2, 10, 'chassisSizes', 'name'),
  'Chassis Owner': createLookupString(2, 100, 'chassisOwners', 'name'),
  'Hazmat': Patterns.YesNo.optional(),
  'Hot': Patterns.YesNo.optional(),
  'Overweight': Patterns.YesNo.optional(),
  'Liquor': Patterns.YesNo.optional(),
  'Genset': Patterns.YesNo.optional(),
  'Scale': Patterns.YesNo.optional(),
  'Domestic': Patterns.YesNo.optional(),
  'EV': Patterns.YesNo.optional(),
  'Waste': Patterns.YesNo.optional(),
  'GDP': Patterns.YesNo.optional(),
  'Rail': Patterns.YesNo.optional(),
  'Street Turn': Patterns.YesNo.optional(),
  'OOG': Patterns.YesNo.optional(),
  'Bonded': Patterns.YesNo.optional(),
  'Use Tariff for combined trips': Patterns.YesNo.optional(),
});

// PerDiem Schema - For container per diem pricing
const PerDiemSchema = z.object({
  'Customers': createLookupString(undefined, 100, 'tmsCustomers', 'company_name').optional(),
  'Owner': createLookupString(undefined, 100, 'containerOwners', 'company_name'),
  'Size': createLookupString(undefined, 10, 'containerSizes', 'name').optional(),
  'Type': createLookupString(undefined, 10, 'containerTypes', 'name'),
  'Tier #1': z.string().max(50).optional(),
  'Tier #2': z.string().max(50).optional(),
  'Tier #3': z.string().max(50).optional(),
  'Tier #4': z.string().max(50).optional(),
  'Import Freedays': z.string().max(50).optional(),
  'Export Freedays': z.string().max(50).optional(),
  'Holiday': z.string().regex(/^(true|false|True|False|TRUE|FALSE)$/).optional(),
  'Free Weekday': z.string().regex(/^(true|false|True|False|TRUE|FALSE)$/).optional(),
});

// Combined Entity Schema
const EntitySchema: Record<string, z.ZodObject<any>> = {
  Load: LoadSchema,
  Carrier: CarrierSchema,
  'Load Tariff': LoadTariffSchema,
  Trailers: TrailersSchema,
  'Truck Owner': TruckOwnerSchema,
  Trucks: TrucksSchema,
  Users: UsersSchema,
  'Charge Profile': ChargeProfileSchema,
  'Chassis Owner': ChassisOwnerSchema,
  Chassis: ChassisSchema,
  People: PeopleSchema,
  Organization: OrganizationSchema,
  'Driver Charge Profile': DriverChargeProfileSchema,
  'Driver Tariff': DriverTariffSchema,
  Drivers: DriversSchema,
  'Carrier Charge Profile': CarrierChargeProfileSchema,
  'Carrier Tariff': CarrierTariffSchema,
  PerDiem: PerDiemSchema,
};

// Updated EntitySchemaLookupIds to match exportEntities.json
const EntitySchemaLookupIds: Record<string, string[]> = {
  Load: [
    'tmsCustomers',
    'containerSizes',
    'containerTypes',
    'containerOwners',
    'branches',
    'chassis',
    'chassisOwners',
    'chassisSizes',
    'chassisTypes',
    'commodities'
  ],
  Carrier: [
    'branches'
  ],
  'Load Tariff': [
    'branches',
    'tmsCustomers'
  ],
  Trailers: [
    'branches'
  ],
  'Truck Owner': [],
  Trucks: [
    'fleetOwners',
    'branches'
  ],
  Users: [
    'branches',
    'getAllPermissionRoles'
  ],
  'Charge Profile': [
    'branches',
    'chargeCodes', 
    'containerSizes',
    'containerTypes',
    'containerOwners',
    'chassisTypes',
    'chassisSizes', 
    'chassisOwners',
    'commodities',
    'tmsCustomers',
    'cityGroups',
    'CSR',
    'zipcodeGroups'
  ],
  'Chassis Owner': [],
  Chassis: [
    'chassisTypes',
    'chassisSizes',
    'chassisOwners',
    'branches'
  ],
  People: [
    'tmsCustomers'
  ],
  Organization: [
    'branches',
    'getTMSFleetCustomers',
    'currencies'
  ],
  'Driver Charge Profile': [
    'branches',
    'chargeCodes',
    'containerSizes',
    'containerTypes',
    'containerOwners',
    'chassisTypes',
    'chassisSizes',
    'chassisOwners',
    'commodities',
    'tmsCustomers',
    'cityGroups',
    'CSR',
    'zipcodeGroups',
    'driverGroups'
  ],
  'Driver Tariff': [
    'branches',
    'tmsCustomers'
  ],
  Drivers: [
    'trucks',
    'driverProfileTypes',
    'branches',
    'timezoneList'
  ],
  'Carrier Charge Profile': [
    'branches',
    'chargeCodes',
    'containerSizes',
    'containerTypes',
    'containerOwners',
    'chassisTypes',
    'chassisSizes',
    'chassisOwners',
    'commodities',
    'tmsCustomers',
    'cityGroups',
    'CSR',
    'zipcodeGroups',
    'carrierGroups'
  ],
  'Carrier Tariff': [
    'branches',
    'tmsCustomers'
  ],
  PerDiem: [
    'containerOwners',
    'containerSizes',
    'containerTypes',
    'tmsCustomers'
  ],
  'Customer Group': [
    'tmsCustomers'
  ],
  'Cities Group': [],
  'Postal/Zip Group': []
};

export {
  EntitySchema,
  EntitySchemaLookupIds,
  Patterns,
  createLookupString,
  createYesNoBoolean,
  createMultiEventPattern,
};