import { z } from 'zod';

// Base schema for common string patterns
const Patterns = {
  Email: z.string().regex(/^[a-zA-Z0-9]([a-zA-Z0-9._-])*[a-zA-Z0-9]@[a-zA-Z0-9]([a-zA-Z0-9-])*[a-zA-Z0-9]\.([a-zA-Z]{2,4})+$/),
  USZip: z.string().regex(/^[0-9]{5}(-[0-9]{4})?$/),
  USState: z.string().regex(/^[A-Z]{2}$/),
  CountryCode: z.string().regex(/^[A-Z]{2}$/),
  Phone10: z.string().regex(/^[0-9]{10}$/),
  DateMMDDYYYY: z.string().regex(/^(0[1-9]|1[0-2])\/(0[1-9]|[12][0-9]|3[01])\/[0-9]{4}$/),
  DateDDMMMYY: z.string().regex(/^(0[1-9]|[12][0-9]|3[01])-(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)-[0-9]{2}$/),
  DateMMDDYY: z.string().regex(/^(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])-[0-9]{2}$/),
  YesNo: z.string().regex(/^(Yes|No)$/),
};

// Carrier Schema
const CarrierSchema = z.object({
  CompanyName: z.string().min(2).max(100),
  ContactName: z.string().min(2).max(100),
  Address: z.string().min(5).max(200),
  Country: Patterns.CountryCode,
  State: Patterns.USState,
  City: z.string().min(2).max(50),
  ZIP: Patterns.USZip,
  LoginEmailAddress: Patterns.Email,
  TenderEmailAddress1: Patterns.Email,
  TenderEmailAddress2: Patterns.Email.optional(),
  TenderEmailAddress3: Patterns.Email.optional(),
  PhoneNumber: Patterns.Phone10,
  SCAC: z.string().regex(/^[A-Z]{4}$/).optional(),
  MC: z.string().regex(/^[0-9]{6,7}$/).optional(),
  USDOTNumber: z.string().regex(/^[0-9]{7,8}$/).optional(),
  ExternalID: z.string().max(50).optional(),
  Branch1: z.string().max(50).optional(),
});

// Load Tariff Schema
const LoadTariffSchema = z.object({
  TariffName: z.string().min(2).max(100),
  TarrifEffectiveStartDate: Patterns.DateMMDDYYYY.optional(),
  TarffEffectiveEndDate: Patterns.DateMMDDYYYY.optional(),
  LoadType: z.string().max(200).optional(),
  Terminal: z.string().max(200).optional(),
  Customer: z.string().max(500).optional(),
  PickUpLocation: z.string().max(500).optional(),
  DeliveryLocation: z.string().max(500).optional(),
  ReturnLocation: z.string().max(500).optional(),
  ChargeProfileName: z.string().min(2).max(100).optional(),
  ChargeName: z.string().min(2).max(100).optional(),
  ChargeDescription: z.string().max(500).optional(),
  UnitofMeasure: z.string().max(50).optional(),
  PercentageBasedOn: z.string().max(200).optional(),
  Effectivedatebasedon: z.string().max(50).optional(),
  ChargeEffectiveStartDate: Patterns.DateMMDDYYYY.optional(),
  ChargeEffectiveEndDate: Patterns.DateMMDDYYYY.optional(),
  AutoAdd: Patterns.YesNo.optional(),
  CalculateFromThisEvent: z.string().max(200).optional(),
  CalculateToThisEvent: z.string().max(200).optional(),
  CalculateInThisEvent: z.string().max(200).optional(),
  CalculateForExactEvents: z.string().max(500).optional(),
  ZipCodeRuleAnyIn: z.string().max(500).optional(),
  ZipCodeRuleNotIn: z.string().max(500).optional(),
  LoadTypeRuleAnyIn: z.string().max(200).optional(),
  LoadTypeRuleNotIn: z.string().max(200).optional(),
  MinimumAmount: z.number().optional(),
  FreeUnits: z.number().optional(),
  Amount: z.number().optional(),
  StartDistance: z.number().optional(),
  EndDistance: z.number().optional(),
});

// Trailers Schema
const TrailersSchema = z.object({
  Trailer: z.string().regex(/^[0-9]{4,10}$/),
  Year: z.string().regex(/^[0-9]{4}$/).optional(),
  Make: z.string().max(50).optional(),
  Model: z.string().max(50).optional(),
  AID: Patterns.DateDDMMMYY.optional(),
  ITD: Patterns.DateDDMMMYY.optional(),
  VIN: z.string().regex(/^[A-Z0-9]{10,17}$/).optional(),
  RegistrationExpiration: Patterns.DateDDMMMYY.optional(),
  InspectionExpiration: Patterns.DateDDMMMYY.optional(),
  LicensePlateState: Patterns.USState.optional(),
  LicensePlate: z.string().regex(/^[A-Z0-9]{1,10}$/).optional(),
  HUTExpiration: Patterns.DateDDMMMYY.optional(),
  TrailerType: z.string().max(50).optional(),
  TrailerSize: z.string().regex(/^[0-9]{2,3}'$/).optional(),
  Branch: z.string().max(100).optional(),
});

// Truck Owner Schema
const TruckOwnerSchema = z.object({
  CompanyName: z.string().min(2).max(100),
  Address: z.string().min(5).max(200),
  DOT: z.string().regex(/^USDOT[0-9]{7}$/).optional(),
  MC: z.string().regex(/^MC[0-9]{6,7}$/).optional(),
  MainContactName: z.string().min(2).max(100).optional(),
  SecondaryContactName: z.string().min(2).max(100).optional(),
  Mobile: Patterns.Phone10.optional(),
  Email: Patterns.Email.optional(),
  TaxIDorEIN: z.string().min(2).max(15).optional(),
  SSN: z.string().min(2).max(15).optional(),
});

// Trucks Schema
const TrucksSchema = z.object({
  EquipmentID: z.string().regex(/^[0-9]{6,10}$/),
  LicenseState: Patterns.USState.optional(),
  LicensePlate: z.string().regex(/^[A-Z0-9]{1,10}$/),
  Year: z.string().regex(/^[0-9]{4}$/).optional(),
  Make: z.string().max(50).optional(),
  Model: z.string().max(50).optional(),
  AID: Patterns.DateMMDDYY.optional(),
  ITD: Patterns.DateMMDDYY.optional(),
  VIN: z.string().regex(/^[A-Z0-9]{10,17}$/).optional(),
  RegistrationExpiration: Patterns.DateMMDDYY.optional(),
  InspectionExpiration: Patterns.DateMMDDYY.optional(),
  HUTExpiration: Patterns.DateMMDDYY.optional(),
  AnnualInspection: Patterns.DateMMDDYY.optional(),
  BobtailInsurance: Patterns.DateMMDDYY.optional(),
  DieselEmission: Patterns.DateMMDDYY.optional(),
  TruckOwner: z.string().max(100).optional(),
  Branch: z.string().max(100).optional(),
});

// Users Schema
const UsersSchema = z.object({
  "First Name": z.string().min(2).max(50),
  "Last Name": z.string().min(2).max(50),
  "Phone": z.string().regex(/^\([0-9]{3}\) [0-9]{3}-[0-9]{4}$/).optional(),
  "Email*": Patterns.Email,
  "Password*": z.string().min(10).regex(/^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#\\$%\\^&\\*])(?=.{10,})/),
  "System Roles*": z.string().regex(/^(?:\\s*(?:Admin|CSR|Sales\\sAgent|Mechanics)\\s*)(?:,\\s*(?:Admin|CSR|Sales\\sAgent|Mechanics)\\s*)*$/),
  "Branch*": z.string().min(2).max(100),
  "Custom Role": z.string().max(100).optional(),
});

// Charge Profile Schema
const ChargeProfileSchema = z.object({
  ChargeProfileName: z.string().min(2).max(100),
  ChargeName: z.string().min(2).max(100).optional(),
  ChargeDescription: z.string().max(500).optional(),
  UnitofMeasure: z.string().max(50).optional(),
  Effectivedatebasedon: z.string().max(50).optional(),
  ChargeEffectiveStartDate: Patterns.DateMMDDYYYY.optional(),
  ChargeEffectiveEndDate: Patterns.DateMMDDYYYY.optional(),
  AutoAdd: Patterns.YesNo.optional(),
  CalculateFromThisEvent: z.string().max(200).optional(),
  CalculateToThisEvent: z.string().max(200).optional(),
  CalculateInThisEvent: z.string().max(200).optional(),
  CalculateForExactEvents: z.string().max(500).optional(),
  ZipCodeRuleAnyIn: z.string().max(500).optional(),
  ZipCodeRuleNotIn: z.string().max(500).optional(),
  LoadTypeRuleAnyIn: z.string().max(200).optional(),
  LoadTypeRuleNotIn: z.string().max(200).optional(),
  CityStateRuleAnyIn: z.string().max(500).optional(),
  MinimumAmount: z.number().optional(),
  FreeUnits: z.number().optional(),
  Amount: z.number().optional(),
  StartDistance: z.number().optional(),
  EndDistance: z.number().optional(),
});

// Chassis Owner Schema
const ChassisOwnerSchema = z.object({
  CompanyName: z.string().min(2).max(100),
  ContactName: z.string().min(2).max(100),
  Phone: Patterns.Phone10,
  Password: z.string().min(10).regex(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^A-Za-z\d])[A-Za-z\d\S]{10,}$/),
  Username: z.string().min(3).max(50).optional(),
  TruckNumber: z.string().max(50).optional(),
  CountryCode: z.string().regex(/^[0-9]{1,3}$/).optional(),
  LicenseState: z.string().min(2).max(50).optional(),
  LicenseNumber: z.string().regex(/^[A-Z0-9]{5,15}$/).optional(),
  Sealink: z.string().regex(/^[0-9]{5,10}$/).optional(),
  EmergencyContactName: z.string().min(2).max(100).optional(),
  EmergencyRelation: z.string().min(2).max(50).optional(),
  EmergencyContactNumber: Patterns.Phone10.optional(),
  BillingEmail: Patterns.Email.optional(),
  ProfileType: z.string().max(50).optional(),
  LicenseExpirationDate: Patterns.DateDDMMMYY.optional(),
  DateOfBirth: Patterns.DateDDMMMYY.optional(),
  DateOfHire: Patterns.DateDDMMMYY.optional(),
  MedicalExpiration: Patterns.DateDDMMMYY.optional(),
  TwicExpiration: Patterns.DateDDMMMYY.optional(),
  SeaLinkExpiration: Patterns.DateDDMMMYY.optional(),
  Branch: z.string().max(100).optional(),
  HomeBranchTimeZone: z.string().max(100).optional(),
  Address: z.string().min(5).max(200),
  City: z.string().min(2).max(50),
  State: z.string().min(2).max(50),
  ZipCode: Patterns.USZip,
  Country: z.string().min(2).max(100),
});

// Chassis Schema
const ChassisSchema = z.object({
  Chassis: z.string().regex(/^[A-Z0-9]{6,20}$/),
  ChassisType: z.string().min(2).max(50),
  ChassisSize: z.string().regex(/^[0-9]{2,3}'$/),
  ChassisOwner: z.string().min(2).max(100),
  Year: z.string().regex(/^[0-9]{4}$/).optional(),
  Make: z.string().max(50).optional(),
  Model: z.string().max(50).optional(),
  AnnualInspectionDate: Patterns.DateDDMMMYY.optional(),
  ITD: Patterns.DateDDMMMYY.optional(),
  Branch: z.string().max(100).optional(),
  LicenseState: z.string().regex(/^[A-Z]{2,}$/),
  LicenseNumber: z.string().regex(/^[A-Z0-9]{1,15}$/),
  VIN: z.string().regex(/^[A-Z0-9]{10,17}$/).optional(),
  Registration: Patterns.DateDDMMMYY.optional(),
  Inspection: Patterns.DateDDMMMYY.optional(),
  Insurance: Patterns.DateDDMMMYY.optional(),
});

// People Schema
const PeopleSchema = z.object({
  Email: Patterns.Email,
  FirstName: z.string().min(2).max(50),
  LastName: z.string().min(2).max(50),
  Mobile: Patterns.Phone10,
  CustomerID: z.string().min(2).max(100),
  Password: z.string().min(10).regex(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^A-Za-z\d])[A-Za-z\d\S]{10,}$/),
  LoadsPermission: z.enum(['True', 'TRUE', 'true', 'False', 'FALSE', 'false']).optional(),
  DroppedContainersPermission: z.enum(['True', 'TRUE', 'true', 'False', 'FALSE', 'false']).optional(),
  AccountPayablePermission: z.enum(['True', 'TRUE', 'true', 'False', 'FALSE', 'false']).optional(),
  InfoPermission: z.enum(['True', 'TRUE', 'true', 'False', 'FALSE', 'false']).optional(),
  BillingPermission: z.enum(['True', 'TRUE', 'true', 'False', 'FALSE', 'false']).optional(),
  DocumentsPermission: z.enum(['True', 'TRUE', 'true', 'False', 'FALSE', 'false']).optional(),
  UploadDocumentsPermission: z.enum(['True', 'TRUE', 'true', 'False', 'FALSE', 'false']).optional(),
  PaymentsPermission: z.enum(['True', 'TRUE', 'true', 'False', 'FALSE', 'false']).optional(),
  TrackingPermission: z.enum(['True', 'TRUE', 'true', 'False', 'FALSE', 'false']).optional(),
  ServiceMessagingPermission: z.enum(['True', 'TRUE', 'true', 'False', 'FALSE', 'false']).optional(),
  SummaryPermission: z.enum(['True', 'TRUE', 'true', 'False', 'FALSE', 'false']).optional(),
  ShipmentTrackingPermission: z.enum(['True', 'TRUE', 'true', 'False', 'FALSE', 'false']).optional(),
  CustomerPermission: z.enum(['True', 'TRUE', 'true', 'False', 'FALSE', 'false']).optional(),
});

// Customers Schema
const CustomersSchema = z.object({
  ProfileName: z.string().min(2).max(100),
  Address: z.string().min(5).max(200),
  City: z.string().min(2).max(50),
  State: Patterns.USState,
  Country: Patterns.CountryCode,
  PostalCode: Patterns.USZip,
  MainContactName: z.string().min(2).max(100).optional(),
  SecondaryContactName: z.string().min(2).max(100).optional(),
  SecondaryPhone: Patterns.Phone10.optional(),
  Mobile: Patterns.Phone10.optional(),
  Email: Patterns.Email.optional(),
  QuickbooksEmail: Patterns.Email.optional(),
  BillingEmail: Patterns.Email.optional(),
  Password: z.string().min(10).regex(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^A-Za-z\d])[A-Za-z\d\S]{10,}$/),
  PaymentTermsMethod: z.string().max(50).optional(),
  PaymentTermsDays: z.number().optional(),
  CreditLimit: z.number().optional(),
  Branch: z.string().min(2).max(100),
  OrganizationType: z.string().min(2).max(50),
  ReceiverEmail: Patterns.Email.optional(),
  McNumber: z.string().regex(/^\([0-9]{3}\) [0-9]{3}-[0-9]{4}$/).optional(),
  FleetCustomer: z.string().max(50).optional(),
  PayType: z.string().max(50).optional(),
  CurrencyType: z.string().regex(/^[A-Z]{3}$/).optional(),
});

// Driver Charge Profile Schema
const DriverChargeProfileSchema = z.object({
  ChargeProfileName: z.string().min(2).max(100),
  ChargeName: z.string().min(2).max(100).optional(),
  ChargeDescription: z.string().max(500).optional(),
  UnitofMeasure: z.string().max(50).optional(),
  Effectivedatebasedon: z.string().max(50).optional(),
  ChargeEffectiveStartDate: Patterns.DateMMDDYYYY.optional(),
  ChargeEffectiveEndDate: Patterns.DateMMDDYYYY.optional(),
  AutoAdd: Patterns.YesNo.optional(),
  CalculateFromThisEvent: z.string().max(200).optional(),
  CalculateToThisEvent: z.string().max(200).optional(),
  IfEvent: z.string().max(200).optional(),
  EventLocation: z.string().max(200).optional(),
  IfEvent1: z.string().max(200).optional(),
  EventTime1: z.string().max(50).optional(),
  EventLocation1: z.string().max(200).optional(),
  ZipCodeRuleAnyIn: z.string().max(500).optional(),
  ZipCodeRuleNotIn: z.string().max(500).optional(),
  LoadTypeRuleAnyIn: z.string().max(200).optional(),
  LoadTypeRuleNotIn: z.string().max(200).optional(),
  MinimumAmount: z.number().optional(),
  FreeUnits: z.number().optional(),
  Amount: z.number().optional(),
  FromLegs: z.string().max(500).optional(),
  FromLegEventLocation: z.string().max(200).optional(),
  ToLegs: z.string().max(200).optional(),
  ToLegEventLocation: z.string().max(200).optional(),
  StartDistance: z.number().optional(),
  EndDistance: z.number().optional(),
  DriverGroup: z.string().max(100).optional(),
});

// Driver Tariff Schema
const DriverTariffSchema = z.object({
  TariffName: z.string().min(2).max(100),
  TarrifEffectiveStartDate: Patterns.DateMMDDYYYY.optional(),
  TarffEffectiveEndDate: Patterns.DateMMDDYYYY.optional(),
  LoadType: z.string().max(200).optional(),
  Terminal: z.string().max(200).optional(),
  Customer: z.string().max(500).optional(),
  PickUpLocation: z.string().max(500).optional(),
  DeliveryLocation: z.string().max(500).optional(),
  ReturnLocation: z.string().max(500).optional(),
  ChargeProfileName: z.string().min(2).max(100).optional(),
  ChargeName: z.string().min(2).max(100).optional(),
  ChargeDescription: z.string().max(500).optional(),
  UnitofMeasure: z.string().max(50).optional(),
  Effectivedatebasedon: z.string().max(50).optional(),
  ChargeEffectiveStartDate: Patterns.DateMMDDYYYY.optional(),
  AutoAdd: Patterns.YesNo.optional(),
  CalculateFromThisEvent: z.string().max(200).optional(),
  CalculateToThisEvent: z.string().max(200).optional(),
  CalculateInThisEvent: z.string().max(200).optional(),
  CalculateForExactEvents: z.string().max(500).optional(),
  ZipCodeRuleAnyIn: z.string().max(500).optional(),
  ZipCodeRuleNotIn: z.string().max(500).optional(),
  LoadTypeRuleAnyIn: z.string().max(200).optional(),
  LoadTypeRuleNotIn: z.string().max(200).optional(),
  MinimumAmount: z.number().optional(),
  FreeUnits: z.number().optional(),
  Amount: z.number().optional(),
  FromLegs: z.string().max(500).optional(),
  FromLegEventLocation: z.string().max(200).optional(),
  ToLegs: z.string().max(200).optional(),
  ToLegEventLocation: z.string().max(200).optional(),
  StartDistance: z.number().optional(),
  EndDistance: z.number().optional(),
  DriverGroup: z.string().max(100).optional(),
});

// Drivers Schema
const DriversSchema = z.object({
  permanentAddress: z.string().optional(),
  truckType: z.array(z.string()).optional(),
  name: z.string(),
  lastName: z.string(),
  username: z.string(),
  email: z.string().regex(/^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/).min(7).max(50),
  mobile: z.string(),
  licence: z.string().optional(),
  licenceNumber: z.string().optional(),
  homeTerminalTimezone: z.string().optional(),
  password: z.string().min(10).regex(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^A-Za-z\d])[A-Za-z\d\S]{10,}$/),
  sealLinkNumber: z.string().optional(),
  billingEmail: z.string().optional(),
  preferredStates: z.array(z.string()).optional(),
  preferredCountry: z.array(z.string()).optional(),
  overWeightCountry: z.array(z.string()).optional(),
  preferredTypesOfLoad: z.array(z.string()).optional(),
  preferredDistance: z.array(z.string()).optional(),
  restrictedLocations: z.array(z.string()).optional(),
  tags: z.array(z.string()).optional(),
  hazmat: z.boolean().optional(),
  liquor: z.boolean().optional(),
  overHeight: z.boolean().optional(),
  reefer: z.boolean().optional(),
  waste: z.boolean().optional(),
  highway: z.boolean().optional(),
  local: z.boolean().optional(),
  gdp: z.boolean().optional(),
  domestic: z.boolean().optional(),
  genset: z.boolean().optional(),
  hot: z.boolean().optional(),
  ev: z.boolean().optional(),
  streetTurn: z.boolean().optional(),
  overweight: z.boolean().optional(),
  permissions: z.array(z.string()).optional(),
  driverRanking: z.number().optional(),
  preferredChassisTypes: z.array(z.string()).optional(),
  preferredMoveTypes: z.array(z.string()).optional(),
  owerWeightStates: z.array(z.string()).optional(),
  socialSecurity: z.string().optional(),
  tablet: z.string().optional(),
  eld: z.string().optional(),
  fuelCard: z.string().optional(),
  ezPass: z.string().optional(),
  driverPreferences: z.boolean().optional(),
  bankAccount: z.string().optional(),
  routing: z.string().optional(),
  tShirtSizes: z.string().optional(),
  disableDriverPay: z.boolean().optional(),
  isDayDriver: z.boolean().optional(),
  profileType: z.array(z.string()).optional(),
  notes: z.string().optional(),
  isSettlementHide: z.boolean().optional(),
  EmergencyContactName: z.string().optional(),
  EmergencyRelation: z.string().optional(),
  newTerminal: z.array(z.string()).optional(),
  termination: z.string().optional(),
  driverHoldStartDt: z.string().optional(),
  driverHoldEndDt: z.string().optional(),
  hst: z.number().optional(),
  registerBusinessName: z.string().optional(),
  invoiceCurrencyWithBranch: z.array(z.string()).optional(),
  currency: z.string().optional(),
  workingDaysHours: z.array(z.string()).optional(),
  country_code: z.string().optional(),
});

// Load Schema
const LoadSchema = z.object({
  Customer: z.string().min(2).max(100),
  LoadType: z.string().max(50).regex(/^(Import|Export|Road)$/),
  PickUpLocation: z.string().max(200),
  Container: z.string().max(20).optional(),
  DeliveryCityState: z.string().max(100),
  ContainerSize: z.string().max(10).optional(),
  ContainerType: z.string().max(10).optional(),
  WeightLBS: z.number().optional(),
  WeightKGS: z.number().optional(),
  DeliveryOrder: z.string().max(50).optional(),
  Owner: z.string().max(100).optional(),
  BookingNumber: z.string().max(50).optional(),
  MasterBillOfLading: z.string().max(50).optional(),
  ContainerETA: Patterns.DateMMDDYYYY.optional(),
  LastFreeDay: Patterns.DateMMDDYYYY.optional(),
  ContainerReturn: z.string().max(200).optional(),
  HookChassisLocation: z.string().max(200).optional(),
  TerminateChassisLocation: z.string().max(200).optional(),
  ReferenceNumber: z.string().max(50).optional(),
  EmptyDate: Patterns.DateMMDDYYYY.optional(),
  DateReturned: Patterns.DateMMDDYYYY.optional(),
  PickUpAptFrom: Patterns.DateMMDDYYYY.optional(),
  DeliveryAptFrom: Patterns.DateMMDDYYYY.optional(),
  ERD: Patterns.DateMMDDYYYY.optional(),
  PerDiemFreeDay: Patterns.DateMMDDYYYY.optional(),
  LoadedDate: Patterns.DateMMDDYYYY.optional(),
  BillingDate: Patterns.DateMMDDYYYY.optional(),
  ChassisNumber: z.string().max(20).optional(),
  ChassisOwner: z.string().max(100).optional(),
  ChassisSize: z.string().max(10).optional(),
  ChassisType: z.string().max(10).optional(),
  CutOffDate: Patterns.DateMMDDYYYY.optional(),
  HouseBillOfLading: z.string().max(50).optional(),
  PickUpNumber: z.string().max(50).optional(),
  PurchaseOrderNumber: z.string().max(50).optional(),
  SealNumber: z.string().max(20).optional(),
  ShipmentNumber: z.string().max(50).optional(),
  Temperature: z.number().optional(),
  Branch: z.string().max(100).optional(),
  VesselName: z.string().max(100).optional(),
  Voyage: z.string().max(50).optional(),
  Commodity: z.string().max(100).optional(),
  Pieces: z.number().optional(),
  Hazmat: z.boolean().optional(),
  Hot: z.boolean().optional(),
  Overweight: z.boolean().optional(),
  Routes: z.string().max(100).regex(/^(Pick And Run \+ Live|Pick And Run \+ Drop & Hook|Prepull \+ Drop & Hook|Prepull \+ Live|One Way Move|Pick And Run \+ Gray Pool|Prepull \+ Gray Pool|Shunt|Pick and Lift \+ Deliver and Lift \+ Return|Pick and Lift \+ Live)$/).optional(),
  Genset: z.boolean().optional(),
  Liquor: z.boolean().optional(),
  Overheight: z.boolean().optional(),
  StreetTurn: z.boolean().optional(),
  Scale: z.boolean().optional(),
});

// Combined Entity Schema
const EntitySchema: Record<string, z.ZodObject<any>> = {
  Load: LoadSchema,
  Carrier: CarrierSchema,
  LoadTariff: LoadTariffSchema,
  Trailers: TrailersSchema,
  TruckOwner: TruckOwnerSchema,
  Trucks: TrucksSchema,
  Users: UsersSchema,
  ChargeProfile: ChargeProfileSchema,
  ChassisOwner: ChassisOwnerSchema,
  Chassis: ChassisSchema,
  People: PeopleSchema,
  Customers: CustomersSchema,
  DriverChargeProfile: DriverChargeProfileSchema,
  DriverTariff: DriverTariffSchema,
  Drivers: DriversSchema,
}

const EntitySchemaLookupIds: Record<string, string[]> = {
  Load: [
    'customers',
    'containerSizes',
    'containerTypes',
    'containerOwners',
    'branches',
    'chassis',
    'chassisOwners',
    'chassisSizes',
    'chassisTypes',
    'commodities'
  ],
  Carrier: [
    'branches'
  ],
  LoadTariff: [],
  Trailers: [
    'branches'
  ],
  TruckOwner: [
    'fleetTruckOwner'
  ],
  Trucks: [
    'trucks',
    'fleetOwners',
    'branches'
  ],
  Users: [
    'users',
    'branches',
    'getAllPermissionRoles'
  ],
  ChargeProfile: [
    'chargeProfile'
  ],
  ChassisOwner: [
    'chassisOwner'
  ],
  Chassis: [
    'chassis',
    'chassisTypes',
    'chassisSizes',
    'chassisOwners',
    'branches'
  ],
  People: [
    'people',
    'tmsCustomers'
  ],
  Customers: [
    'customers',
    'branches',
    'getTMSFleetCustomers',
    'currencies'
  ],
  DriverChargeProfile: [
    'driverChargeProfile'
  ],
  DriverTariff: [
    'driverTariff'
  ],
  Drivers: [
    'drivers',
    'trucks',
    'driverProfileTypes',
    'branches',
    'timezoneList'
  ],
};

export {
  EntitySchema,
  EntitySchemaLookupIds
};